services:
  vrn_django:
    build:
      context: .
    container_name: vrndjango
    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../:/vrn_assignment
    ports:
      - "8006:8000"
    depends_on:
      - vrn_postgres
  vrn_postgres:
    image: postgres:16
    container_name: vrnpostgres
    ports:
      - "5438:5432"
    restart: always
    env_file:
      - ../env/postgres.env
    volumes:
      - db_data:/var/lib/postgresql/data
  vrn_pgadmin:
    image: dpage/pgadmin4
    container_name: vrnpgadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - vrn_postgres
    env_file:
      - ../env/pgadmin.env
volumes:
  db_data: